import Footer from "../components/Footer"
import Header from "../components/Header"

const About = () => {

	return (<>
		<Header />
		<h1>About Page</h1>
		<p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Non voluptate dolores laborum est natus sapiente, placeat tempore reiciendis ab consequuntur veniam impedit nostrum nemo facere enim doloribus earum. Magni, recusandae.
			Alias aliquam libero hic distinctio fugit. Maxime iure, architecto blanditiis magni odio quisquam modi iusto vel unde, aliquam perferendis magnam possimus pariatur qui repellat illum delectus accusantium autem provident placeat!
			Maxime hic at ut, magnam eaque, eos in accusamus debitis inventore commodi voluptates magni deserunt saepe quis? Mollitia expedita, ducimus dicta laborum facilis quod similique veniam autem temporibus minima illum.
			Ducimus placeat ab aut unde tenetur nostrum. Dicta aliquid eveniet atque distinctio ipsum amet delectus vero et, illum nesciunt laudantium nemo doloribus consequatur soluta voluptates cupiditate eaque porro obcaecati cum?
			Necessitatibus ut quos quia ipsum error totam a. Rerum voluptatibus magnam dolores nostrum necessitatibus est repudiandae error at fuga praesentium, corrupti hic velit minima accusantium facilis. Praesentium veritatis necessitatibus distinctio.
			Nostrum, hic, iusto aut illum, cumque alias quisquam id explicabo dignissimos dolorum aperiam recusandae in commodi eligendi? Dicta deleniti earum dignissimos tempore quis, vitae itaque commodi, illum qui impedit aliquam.
			Distinctio cumque expedita ab, doloribus voluptatibus omnis blanditiis iure maxime beatae rem nam optio ea illum! Incidunt fuga quam consectetur aliquam dolore! Atque excepturi corporis, cumque culpa accusantium delectus cupiditate?
			Nulla, earum. Ex voluptates voluptas sapiente ipsum nesciunt perferendis voluptatem cum, eius pariatur recusandae dolor asperiores unde. Cumque ipsa, quod, eveniet corrupti consequatur optio laborum, soluta earum sunt voluptates natus.
			Excepturi aut odio sapiente deserunt ut? Quia tempore accusantium totam distinctio laborum quis laboriosam maxime voluptate quasi iure adipisci aliquam, illum explicabo, incidunt, eum unde dolores possimus voluptatibus. Ea, reprehenderit.
			Ab quo in eos aspernatur corrupti illum voluptatem iste voluptatibus perspiciatis cupiditate tempora ex, est dolores dicta earum, sed dolorem, officia illo. Minima aperiam vitae optio tempora recusandae eligendi officiis.
			Nesciunt officia ratione, labore quibusdam sit sequi corrupti at nam adipisci vitae numquam eaque voluptate error natus iusto recusandae reprehenderit minus cumque aspernatur voluptates? Velit, eos. Quibusdam vel minus ipsum!
			Quibusdam iusto omnis debitis quaerat fugit eos odio natus et fugiat commodi, alias, incidunt optio perspiciatis labore sint inventore nobis aliquam dolorem nisi eveniet, soluta assumenda? Dolorem, iste? Sed, eaque?
			Maxime, dolore odit est distinctio optio eligendi alias. Omnis, inventore quasi debitis dignissimos placeat mollitia tempore porro magni cum culpa voluptate ipsum veritatis. Qui iure explicabo modi ratione eveniet dolorum.
			Maxime nulla similique impedit esse atque totam. Consectetur consequuntur pariatur, quos accusamus nihil quisquam repudiandae facere harum deserunt recusandae debitis commodi itaque vel a voluptatum beatae nulla rem! Omnis, recusandae.
			Eveniet quidem velit, exercitationem repellat molestias dolor architecto obcaecati autem, perferendis blanditiis dolore. Ipsum molestiae id corporis qui quas explicabo, est ipsam magni adipisci omnis distinctio nobis dicta iste laboriosam!
			Facere quae quod ipsa officiis nulla iusto nostrum recusandae provident architecto reiciendis inventore, suscipit consectetur cum sequi necessitatibus soluta? Illo magnam dolore sit, a incidunt id cumque pariatur quos veniam.
			Labore beatae iusto quidem velit impedit aliquam numquam distinctio porro enim ullam asperiores deserunt nemo ex, voluptatem quas hic, assumenda optio facilis alias expedita, corrupti doloribus modi natus. Dignissimos, delectus?
			Quae, consectetur? Animi fugit modi ipsum cupiditate quas omnis, illum laudantium, ad numquam veniam repellat nulla, nobis consectetur. Beatae quaerat vitae id atque illo voluptatem ipsam iusto ducimus facere! Impedit!
			Odio doloremque accusantium ullam animi itaque obcaecati corrupti at ad delectus reiciendis error hic vero quis, pariatur, neque commodi aspernatur officia quos tenetur! Iusto magni consectetur tenetur dignissimos rem? Reprehenderit.
			Delectus veniam atque officiis nisi a illo iusto odio consequuntur inventore fugiat reprehenderit, ipsum commodi obcaecati voluptatum autem nulla deserunt? Deserunt sequi perspiciatis asperiores repudiandae? Labore voluptas eum dicta minus?
			Illum eos sed, velit facilis neque quos ex consectetur unde obcaecati nemo porro cupiditate ad iusto alias deleniti eaque harum voluptatibus vero sint saepe accusamus odio? Voluptate quisquam voluptates molestias.
			Maxime id nisi dolorem magni cumque tempora eos sint quasi expedita, nam pariatur quas quos officia numquam molestias magnam dolores asperiores illo labore ratione. Dolorem laborum amet maxime corrupti porro.
			Aperiam magnam incidunt reprehenderit exercitationem officiis laudantium provident veritatis impedit enim modi totam tempora beatae dolorum nam ut minima, quae animi, architecto eligendi? Consectetur accusamus tempora neque saepe facilis vero.
			Possimus cupiditate reprehenderit quasi quam eum molestiae dolorum? In dolorum vero esse harum magni. Vitae dolor aliquid non illum mollitia nemo eligendi obcaecati, rem temporibus amet! Consectetur ut aliquid modi?
			Doloremque dolores minus optio neque excepturi quo, perspiciatis dignissimos pariatur repellat quia magnam labore nostrum id earum esse ipsam quasi mollitia eveniet delectus. Quo magnam officia totam numquam modi pariatur?
			Temporibus quaerat, totam, impedit cumque cupiditate, rerum voluptate fugiat laboriosam ad veniam rem delectus atque modi nesciunt deserunt quisquam minus non optio facere minima accusantium earum? Consequatur accusantium cumque temporibus.
			Vero, temporibus. Repudiandae vel explicabo officiis placeat culpa voluptates, optio eveniet ullam, debitis neque iste. Quis id, odit ratione inventore deserunt itaque, ea ipsam velit excepturi, quasi atque repellendus quo.
			Error dicta quasi, facere ratione deleniti earum nostrum architecto placeat, harum provident eius officiis vero veritatis molestias quisquam ad culpa praesentium dolores sunt. Odit vel quaerat sunt voluptatum magni impedit.
			Perspiciatis officiis placeat architecto, maiores aut cumque delectus doloremque illo quod qui quibusdam eius nulla explicabo quas ad, non facilis labore consectetur praesentium optio! At possimus nulla eum fugit? Laborum.
			Aliquid quia fugit facilis quod recusandae placeat, modi quae cupiditate libero architecto sapiente pariatur iure quis? Iure libero, ad aperiam ab quidem quasi quas sed ex doloribus exercitationem consequatur ratione!
			Delectus repudiandae amet ut enim odio? Distinctio in molestiae quae, unde fugiat ipsam, accusamus vel ullam dolor eveniet sint eligendi voluptatem dolore adipisci mollitia nisi eos quia doloribus? Accusamus, molestiae.
			Illum sit laboriosam itaque eos iste neque sunt atque eius enim pariatur? Nostrum, similique cumque rerum odit magnam molestiae iure natus fuga expedita enim, iste nemo nam, dicta recusandae sed.
			Corrupti ab in asperiores sed nostrum commodi debitis. Inventore reprehenderit, sint officiis dignissimos in ea debitis consequatur nihil dolor quidem tenetur atque, ullam eligendi, nemo aperiam quod? Tempore, hic explicabo.
			Aliquam possimus eius, explicabo ad ut deserunt assumenda blanditiis architecto repellat voluptatibus incidunt fugiat. Facere delectus, provident obcaecati ut, et dicta laboriosam nemo molestiae corporis reprehenderit atque veniam necessitatibus! Quidem.
			Voluptates, dolorum quaerat unde cupiditate architecto itaque et corrupti veritatis quia omnis nesciunt fugit commodi nihil, amet dolorem fugiat modi accusantium magni cumque, adipisci eos dignissimos vitae. Quam, culpa amet.
			Perferendis autem a dolore ipsam voluptates provident fuga. Consequatur consectetur veniam, ratione voluptatum, suscipit ad eum tenetur unde accusantium et cupiditate vel dicta officiis rem voluptatem aliquid? Adipisci, quis. Laudantium?
			Odit, delectus aperiam beatae earum perferendis sunt quasi ut, deleniti, cumque iure corporis? Tempore necessitatibus modi molestias accusamus, iure, reiciendis at doloremque ipsum, vel voluptatibus vero cum? Facilis, commodi inventore.
			Suscipit, voluptatibus. Tenetur earum modi inventore eius vitae atque id beatae autem, dolores maxime ipsa libero, quas quis, aliquam laboriosam excepturi natus tempore delectus expedita temporibus? Cumque ut optio sint.
			Repellendus nulla laborum saepe ipsum sit voluptas quisquam accusantium laudantium necessitatibus quos placeat iste deserunt velit eveniet reiciendis impedit deleniti dicta, pariatur, sint beatae quam numquam quia ad quis? Accusantium!
			Porro sequi officia ipsum quisquam eveniet mollitia illum eius amet et maiores accusantium magni cum sapiente quas facere, sint est aperiam in necessitatibus corrupti. Repudiandae soluta dicta nulla omnis sint.
			Consectetur cupiditate, est repudiandae iusto eaque quaerat nemo. Officia quaerat, veritatis totam quae pariatur odit unde aspernatur, quidem, numquam temporibus cupiditate. A eligendi autem nesciunt, ex asperiores delectus rerum. Nihil?
			Dignissimos nisi quae recusandae est incidunt quia corporis exercitationem mollitia rerum. Quibusdam, harum eius quis aspernatur temporibus quidem iure id esse veniam totam laudantium laboriosam voluptatibus voluptate sapiente doloribus eligendi.
			Natus officiis maxime dignissimos laborum quidem blanditiis iste quam cum distinctio consequatur sapiente tenetur repellendus totam excepturi, commodi nam architecto ea facilis soluta delectus debitis? Iure quod quo sequi magni.
			Cupiditate similique accusamus a, impedit voluptatem saepe sed quos quibusdam voluptates sit possimus exercitationem id inventore optio consequuntur iure odit vel, illum beatae ipsa obcaecati minima ipsum. Voluptate, eveniet consectetur.
			Sint ut minus iusto quod similique accusantium enim sit a tempora est voluptatum, quidem sed et, dicta dolores totam odit quam. Vero doloribus temporibus libero officiis sapiente ipsa veniam soluta.
			Esse, nobis beatae! Veniam ut est ullam, voluptatibus consectetur a esse sapiente ratione error distinctio, ducimus mollitia sequi, nulla officia minus architecto nobis fugit tempore quo. Reiciendis, praesentium? Ipsa, optio!
			Perspiciatis nam placeat, excepturi ipsa quaerat reiciendis iure obcaecati, mollitia ad voluptatum aliquid praesentium! Dolor maiores corporis impedit illo officia debitis tempore nobis, magni dignissimos sunt dolores quas repellat quidem?
			Voluptas ipsum at reiciendis ducimus, esse officia illo vero accusantium tempora corporis cupiditate cumque vitae necessitatibus animi? Nesciunt nostrum error dignissimos optio? Quis similique voluptatibus exercitationem, reprehenderit nam repellat aperiam!
			Qui magni consequuntur molestias dolores, nihil excepturi alias consequatur minus illum dolor voluptatem fuga ea natus, voluptatibus voluptatum corporis dolore. Animi sint autem eum aperiam architecto totam id placeat voluptate?
			Dolorum velit at vero sequi et ullam quasi mollitia ad adipisci? Libero voluptatem, est tempore voluptas minima ut, architecto, amet ullam ipsa facere incidunt esse quibusdam cumque commodi dicta quam.
			Facere dolorum ducimus, eveniet nostrum maiores vero soluta officiis, expedita fugit distinctio praesentium. Tempore praesentium impedit eos saepe illo, nostrum voluptas assumenda dolorem qui tempora ducimus, velit iure alias optio.
			Perspiciatis deleniti blanditiis cumque sunt corrupti! Odit accusamus hic, praesentium facilis nulla cumque sapiente molestias qui doloribus quis veniam harum tempora nisi maxime velit delectus culpa, ratione tenetur vero enim?
			Odit veritatis impedit quaerat recusandae perspiciatis libero, nisi nobis ipsam nihil similique fugit minus quod reiciendis reprehenderit hic obcaecati aliquid sunt tempore necessitatibus inventore. Consequatur, iusto. Sapiente aliquid ipsam fugiat?
			Possimus modi debitis temporibus perspiciatis totam impedit veritatis reiciendis commodi laudantium dolorem asperiores tenetur, blanditiis id vel et, fugit in vitae molestiae odio atque, quis magni amet iusto. Reprehenderit, amet.
			A id maxime iste expedita optio, delectus maiores odio temporibus ad atque et reprehenderit voluptatum perferendis deleniti quaerat dolore eligendi incidunt quisquam quis ipsum? Eveniet, eaque? Sit fuga maiores similique.
			Dignissimos aliquam error perferendis consequuntur nulla necessitatibus labore dolores obcaecati, deleniti temporibus odit earum, distinctio pariatur facilis ipsa culpa rem. Sequi tempore illum nulla voluptatem reiciendis minus, doloremque mollitia dignissimos?
			Dignissimos incidunt doloremque commodi in impedit fugiat. Magni expedita officia numquam provident, voluptatem soluta assumenda repellendus voluptate consequatur consequuntur mollitia nostrum architecto dolorem illo. Placeat quasi esse ducimus facere tempora!
			Placeat sequi sunt voluptate illo dolorem modi perferendis, rerum saepe quisquam corrupti, at cum enim pariatur! Ipsam, quas! Voluptas, officiis illum. Explicabo ab molestiae amet quibusdam alias, doloremque iure maiores.
			Magnam atque nihil maxime praesentium provident nulla culpa animi temporibus eum, quia officia natus iste accusantium vel ut blanditiis voluptas voluptate libero, consequatur fugit. Ab recusandae maiores cum sit impedit.
			Omnis ea doloremque possimus, odit modi, iusto impedit itaque ipsa, at quam asperiores corporis tenetur rerum facere? Voluptates totam veritatis odit magnam illo earum fugiat assumenda incidunt obcaecati, praesentium enim?
			Labore ab iusto non beatae, asperiores reiciendis placeat inventore odio quis, laborum ipsa velit ea. Iure laudantium debitis nobis quos. Quo corporis ut cumque distinctio doloremque nesciunt sequi, voluptate beatae.
			Autem ratione adipisci totam beatae unde, minima laborum dolorem illo excepturi iure laudantium fugit, possimus porro reprehenderit sunt dolor numquam. Impedit sequi eligendi repudiandae voluptatum nihil animi quidem labore aperiam.
			Inventore maiores sapiente iure architecto excepturi! Architecto itaque excepturi magni asperiores, soluta odio modi aperiam veniam. Adipisci ex eveniet incidunt voluptatibus nemo voluptatum ad, fuga in esse distinctio atque ea.
			Repudiandae ab maxime odit quos libero recusandae, deleniti natus odio architecto ullam quod velit itaque expedita adipisci, soluta corporis reprehenderit excepturi ipsa ratione, blanditiis assumenda consequatur porro doloribus? Ea, id.
			Ut beatae alias eligendi sit aliquam accusantium vitae cumque! Aliquam ea voluptas iusto delectus reiciendis nulla inventore eius porro, eos omnis? Quod explicabo ullam dolor nostrum amet ex molestias officiis.
			Quibusdam omnis aspernatur, nisi magni minima architecto porro unde ullam reiciendis aut fugit facere nostrum odio sapiente quisquam fuga, maiores molestiae saepe sit cum soluta numquam nobis repudiandae praesentium! Ducimus!
			Ratione alias esse facilis vero! Qui aut soluta quaerat consequatur eius placeat alias tempora quia, laudantium, officiis reiciendis culpa deleniti impedit architecto a. Nesciunt quibusdam error cumque sint. Quos, neque.
			Totam, a adipisci officia ea blanditiis molestiae pariatur eius, eligendi error quo repellendus soluta ducimus beatae distinctio consequatur, quibusdam suscipit? Excepturi quis molestias voluptatibus ab vel eius nostrum eligendi perferendis.
			Nostrum nulla voluptas assumenda maxime molestiae modi omnis exercitationem laborum autem, illum at, alias laudantium delectus debitis consectetur fugiat dolorum eaque eos eum, porro repudiandae optio quos? Atque, aut ipsa!
			Voluptatum minima fugiat repudiandae necessitatibus iste. Esse veritatis sint sed voluptas accusantium laborum quas tempore, magni at impedit inventore alias! Iusto soluta nemo nobis rerum, quo eaque ut corporis sequi!
			Deserunt excepturi voluptas, quasi placeat illo quae maiores esse eum inventore debitis asperiores quaerat dolorem nemo fugiat voluptate tempora neque consequatur eaque cumque, dolorum doloremque quisquam. Eos necessitatibus unde nisi!
			Modi voluptates non possimus sunt voluptas, accusamus in. Explicabo optio tempore omnis adipisci repellat reprehenderit similique inventore quia a laudantium? Sunt, in? Ab laudantium qui vero sint ratione dolorum vitae.
			Repellat, eum impedit. Maxime minus eius reiciendis, facilis perferendis ut adipisci corrupti ea reprehenderit tempore cupiditate accusantium illum amet eos non distinctio ab nostrum magni? Id sed enim neque voluptatibus!
			Vitae eum officiis, adipisci maxime ab hic iusto similique placeat nulla iure corrupti reiciendis minus optio at illum? Architecto laboriosam ex nostrum nisi reiciendis beatae porro repudiandae commodi tenetur voluptates?
			Omnis atque, minima hic eum possimus sapiente sequi perferendis accusamus? Saepe, reprehenderit itaque aperiam mollitia impedit eius harum hic omnis dolore quae aliquid corporis sunt praesentium ea repellat adipisci! Quo?
			Magnam voluptas nam autem eos obcaecati porro enim suscipit tempore sit voluptate quis nesciunt excepturi culpa eum ut iste assumenda, quaerat illum recusandae ad sequi ex repellat dolore fugiat. Perferendis!
			Nam pariatur itaque beatae, veritatis deserunt consequuntur incidunt, voluptates quibusdam id accusamus temporibus. Fugiat cum nam consequatur quibusdam laudantium ullam illo recusandae ex delectus, beatae neque dolor tenetur adipisci amet.
			Aspernatur et minus alias delectus explicabo saepe doloribus magni veniam libero voluptatum. Quod atque a maxime voluptas ut ab debitis accusamus tempora dolorum, vero eum fuga ea consequatur quaerat nostrum!
			Quibusdam odio accusantium nostrum, officiis tempore quasi magnam voluptatum iure? Culpa ut molestiae aperiam neque? Facilis quisquam doloribus officiis dolor sint hic quo alias similique libero veritatis asperiores, vel at?
			Atque nisi modi repellendus soluta laudantium veniam, saepe sed in architecto iste qui quae eius corrupti cupiditate quis accusamus facere magnam, velit vel. Sit ducimus necessitatibus corporis. Quasi, quos quae?
			Porro nemo placeat iste molestias voluptates sed voluptatem quibusdam rerum at repudiandae exercitationem, magni nihil eaque atque beatae asperiores suscipit culpa quisquam praesentium adipisci possimus. Rem pariatur eos accusamus voluptatibus.
			Ut cum nostrum tempore dolorum aliquid cupiditate nam earum quos consectetur at veniam, ullam dolores repudiandae magni optio recusandae doloremque? Vero, numquam. Magni, excepturi debitis quo deleniti quis eaque similique.
			Voluptatem perspiciatis, recusandae eius, quia repellat delectus quos consequatur dignissimos molestiae nesciunt alias, voluptas vitae nulla provident tempora a qui necessitatibus enim quisquam cumque totam ratione? Recusandae reprehenderit eveniet repudiandae.
			Nam distinctio consectetur hic qui eum, itaque illum repudiandae quas, sit iste accusantium rerum assumenda quibusdam eos architecto voluptatem eligendi dignissimos sequi consequatur modi reprehenderit? Totam magni minima sapiente veritatis!
			Repellendus corrupti eum impedit non laboriosam! Accusamus totam ratione nam, provident numquam minus perspiciatis debitis quo tempore cum! Dolores a quos architecto minima rem qui laudantium repudiandae saepe animi at.
			Aliquam officia consequuntur quod, quis, adipisci laudantium ea neque, culpa nobis eligendi ex architecto repellendus saepe consequatur quaerat reprehenderit libero dolores. Cumque dolorem consectetur et magni reiciendis consequuntur, architecto delectus!
			Tenetur eius soluta neque odio non blanditiis hic tempora suscipit, error id ullam consequuntur maxime vero libero. Adipisci amet nostrum fugiat. Ab hic cum consequuntur odio iusto saepe quos possimus?
			Rem ad eius, voluptatibus laudantium aliquid voluptatum molestiae id obcaecati aperiam eligendi accusantium, deserunt repellendus veniam cupiditate maxime debitis ducimus temporibus. Atque aliquam nam vitae architecto ratione accusantium necessitatibus porro!
			Vero laudantium unde nam perferendis id enim sunt quaerat nihil expedita vel fuga harum dolorem quibusdam aspernatur vitae ex pariatur delectus eaque, dicta beatae praesentium consequatur amet aliquid voluptatum. Hic.
			Aperiam tempore, natus nisi aliquam, quos dolores ipsum eum modi beatae ratione neque consequuntur ducimus ipsa perspiciatis minima labore optio reprehenderit hic explicabo libero voluptatibus debitis. Soluta fugiat repellendus neque.
			Commodi quo perferendis voluptas, doloribus minima possimus sequi iste sapiente sed rerum modi iusto atque quis fugit quidem aspernatur officiis, quisquam, ipsum temporibus recusandae. Similique hic doloribus nesciunt neque illo.
			Esse voluptate optio doloremque vitae inventore dignissimos dolorum reprehenderit, tenetur quasi placeat. Accusamus, sunt praesentium! Quisquam ullam molestias quasi exercitationem iusto eum, corrupti veniam, asperiores soluta quae repudiandae distinctio saepe.
			Iusto animi cum suscipit totam porro quisquam asperiores non laboriosam debitis dolorum dicta molestias magnam nemo tempore, ipsam, reiciendis facilis vero inventore ratione consequatur quidem. Nemo praesentium consequatur soluta sit.
			Aperiam facilis sunt ipsam error impedit. Voluptatum nesciunt iure fuga, architecto tenetur modi exercitationem voluptatem nihil ab odio quae autem assumenda beatae velit sapiente perferendis recusandae ex voluptatibus. Dolorem, illo!
			Deleniti fuga, quia nesciunt quasi ut vitae voluptate delectus enim, rerum repudiandae minus, tempore sequi labore. Omnis, qui. Assumenda optio quod tempora dicta soluta, veniam laudantium aspernatur sequi facere in!
			Explicabo quasi corrupti voluptatem impedit temporibus repellendus deserunt ducimus eveniet eum, quibusdam repellat quo obcaecati facere natus libero accusamus aliquam, magnam eligendi iure nemo sit nobis praesentium enim veritatis. Similique.
			Ex ab esse aut molestias mollitia omnis accusamus reiciendis sint at totam! Voluptates temporibus aperiam iste debitis earum. Dolorem deleniti corporis, nostrum veritatis in minima odio cumque architecto praesentium blanditiis!
			Ex quidem ut ea, veritatis nesciunt facere perspiciatis dolorem, aspernatur voluptatibus iure adipisci ducimus perferendis excepturi mollitia tenetur possimus officiis deserunt fugit ipsa facilis sunt temporibus sed reprehenderit non. Blanditiis.
			Culpa commodi nemo totam tenetur saepe aut, molestias dicta maxime rem illum porro dolore eos asperiores facilis voluptas dignissimos tempora magni placeat alias, ab error reprehenderit quam excepturi exercitationem. Nostrum?
			Ducimus nobis ea omnis tenetur nisi veritatis aliquam unde laboriosam incidunt architecto, labore nostrum voluptas quae, doloribus id ipsum non quam porro reiciendis dolores possimus? Laudantium omnis esse vero odio.</p>
		<Footer />
	</>)
}

export default About